language: python
python:
    - 2.7
    - 3.5
# command to install dependencies
#install: "pip install -r requirements.txt"
script:
    # The first command creates the virtual environment
    - python bench.py list
    - python bench.py list_groups
    - python bench.py run --debug-single-sample -b all
